create table
  public.cart_item (
    id integer generated by default as identity,
    quantity integer not null,
    cart_id integer not null,
    item_sku text not null,
    constraint cart_item_pkey primary key (id),
    constraint cart_item_id_key unique (id),
    constraint cart_item_item_sku_key unique (item_sku),
    constraint cart_item_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_item_item_sku_fkey foreign key (item_sku) references potions (item_sku)
  ) 

create table
  public.carts (
    id integer generated by default as identity,
    name text null,
    constraint carts_pkey primary key (id)
  )

create table
  public.potions (
    id bigint generated by default as identity,
    inventory integer not null,
    price integer null,
    item_sku text not null,
    name text not null,
    type integer[] null,
    constraint potions_pkey primary key (id),
    constraint potions_item_sku_key unique (item_sku),
    constraint potions_name_key unique (name)
  )
